#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountPayableAPI
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Sandbox")]
	public partial class AccountsPayableDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAPMeasure(APMeasure instance);
    partial void UpdateAPMeasure(APMeasure instance);
    partial void DeleteAPMeasure(APMeasure instance);
    #endregion
		
		public AccountsPayableDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SandboxConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AccountsPayableDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AccountsPayableDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AccountsPayableDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AccountsPayableDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<APMeasure> APMeasures
		{
			get
			{
				return this.GetTable<APMeasure>();
			}
		}
		
		public System.Data.Linq.Table<Contract> Contracts
		{
			get
			{
				return this.GetTable<Contract>();
			}
		}
		
		public System.Data.Linq.Table<depts_and_division> depts_and_divisions
		{
			get
			{
				return this.GetTable<depts_and_division>();
			}
		}
		
		public System.Data.Linq.Table<Expenditure> Expenditures
		{
			get
			{
				return this.GetTable<Expenditure>();
			}
		}
		
		public System.Data.Linq.Table<AP_Measure_Final> AP_Measure_Finals
		{
			get
			{
				return this.GetTable<AP_Measure_Final>();
			}
		}
		
		public System.Data.Linq.Table<Abandoned_Property_Combined_Source> Abandoned_Property_Combined_Sources
		{
			get
			{
				return this.GetTable<Abandoned_Property_Combined_Source>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="FMS.APMeasures")]
	public partial class APMeasure : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RowId;
		
		private string _user_code;
		
		private string _vendor_number;
		
		private string _indxctrl;
		
		private string _AP_Document;
		
		private string _AP_Ref_Document;
		
		private System.Nullable<System.DateTime> _Invoice_Date;
		
		private System.Nullable<System.DateTime> _Date_Received;
		
		private System.Nullable<System.DateTime> _Enter_Date;
		
		private System.Nullable<System.DateTime> _Check_Date;
		
		private System.Nullable<double> _Invoice_to_Received_days;
		
		private System.Nullable<double> _Received_to_Check_days;
		
		private System.Nullable<double> _Invoice_to_Check_days;
		
		private string _Pmt_Data;
		
		private string _check_no;
		
		private string _pmt_name;
		
		private string _desc_30;
		
		private string _Comment;
		
		private System.Nullable<double> _amount;
		
		private string _GL_Acct;
		
		private string _GL_Dept;
		
		private string _Ledger_Batch;
		
		private string _Requestor;
		
		private string _Last_Access;
		
		private string _Last_Login;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRowIdChanging(int value);
    partial void OnRowIdChanged();
    partial void Onuser_codeChanging(string value);
    partial void Onuser_codeChanged();
    partial void Onvendor_numberChanging(string value);
    partial void Onvendor_numberChanged();
    partial void OnindxctrlChanging(string value);
    partial void OnindxctrlChanged();
    partial void OnAP_DocumentChanging(string value);
    partial void OnAP_DocumentChanged();
    partial void OnAP_Ref_DocumentChanging(string value);
    partial void OnAP_Ref_DocumentChanged();
    partial void OnInvoice_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnInvoice_DateChanged();
    partial void OnDate_ReceivedChanging(System.Nullable<System.DateTime> value);
    partial void OnDate_ReceivedChanged();
    partial void OnEnter_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnEnter_DateChanged();
    partial void OnCheck_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnCheck_DateChanged();
    partial void OnInvoice_to_Received_daysChanging(System.Nullable<double> value);
    partial void OnInvoice_to_Received_daysChanged();
    partial void OnReceived_to_Check_daysChanging(System.Nullable<double> value);
    partial void OnReceived_to_Check_daysChanged();
    partial void OnInvoice_to_Check_daysChanging(System.Nullable<double> value);
    partial void OnInvoice_to_Check_daysChanged();
    partial void OnPmt_DataChanging(string value);
    partial void OnPmt_DataChanged();
    partial void Oncheck_noChanging(string value);
    partial void Oncheck_noChanged();
    partial void Onpmt_nameChanging(string value);
    partial void Onpmt_nameChanged();
    partial void Ondesc_30Changing(string value);
    partial void Ondesc_30Changed();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnamountChanging(System.Nullable<double> value);
    partial void OnamountChanged();
    partial void OnGL_AcctChanging(string value);
    partial void OnGL_AcctChanged();
    partial void OnGL_DeptChanging(string value);
    partial void OnGL_DeptChanged();
    partial void OnLedger_BatchChanging(string value);
    partial void OnLedger_BatchChanged();
    partial void OnRequestorChanging(string value);
    partial void OnRequestorChanged();
    partial void OnLast_AccessChanging(string value);
    partial void OnLast_AccessChanged();
    partial void OnLast_LoginChanging(string value);
    partial void OnLast_LoginChanged();
    #endregion
		
		public APMeasure()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RowId
		{
			get
			{
				return this._RowId;
			}
			set
			{
				if ((this._RowId != value))
				{
					this.OnRowIdChanging(value);
					this.SendPropertyChanging();
					this._RowId = value;
					this.SendPropertyChanged("RowId");
					this.OnRowIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_code", DbType="VarChar(50)")]
		public string user_code
		{
			get
			{
				return this._user_code;
			}
			set
			{
				if ((this._user_code != value))
				{
					this.Onuser_codeChanging(value);
					this.SendPropertyChanging();
					this._user_code = value;
					this.SendPropertyChanged("user_code");
					this.Onuser_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vendor_number", DbType="VarChar(50)")]
		public string vendor_number
		{
			get
			{
				return this._vendor_number;
			}
			set
			{
				if ((this._vendor_number != value))
				{
					this.Onvendor_numberChanging(value);
					this.SendPropertyChanging();
					this._vendor_number = value;
					this.SendPropertyChanged("vendor_number");
					this.Onvendor_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indxctrl", DbType="VarChar(50)")]
		public string indxctrl
		{
			get
			{
				return this._indxctrl;
			}
			set
			{
				if ((this._indxctrl != value))
				{
					this.OnindxctrlChanging(value);
					this.SendPropertyChanging();
					this._indxctrl = value;
					this.SendPropertyChanged("indxctrl");
					this.OnindxctrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[AP Document]", Storage="_AP_Document", DbType="VarChar(50)")]
		public string AP_Document
		{
			get
			{
				return this._AP_Document;
			}
			set
			{
				if ((this._AP_Document != value))
				{
					this.OnAP_DocumentChanging(value);
					this.SendPropertyChanging();
					this._AP_Document = value;
					this.SendPropertyChanged("AP_Document");
					this.OnAP_DocumentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[AP Ref Document]", Storage="_AP_Ref_Document", DbType="VarChar(50)")]
		public string AP_Ref_Document
		{
			get
			{
				return this._AP_Ref_Document;
			}
			set
			{
				if ((this._AP_Ref_Document != value))
				{
					this.OnAP_Ref_DocumentChanging(value);
					this.SendPropertyChanging();
					this._AP_Ref_Document = value;
					this.SendPropertyChanged("AP_Ref_Document");
					this.OnAP_Ref_DocumentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Invoice Date]", Storage="_Invoice_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Invoice_Date
		{
			get
			{
				return this._Invoice_Date;
			}
			set
			{
				if ((this._Invoice_Date != value))
				{
					this.OnInvoice_DateChanging(value);
					this.SendPropertyChanging();
					this._Invoice_Date = value;
					this.SendPropertyChanged("Invoice_Date");
					this.OnInvoice_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Date Received]", Storage="_Date_Received", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date_Received
		{
			get
			{
				return this._Date_Received;
			}
			set
			{
				if ((this._Date_Received != value))
				{
					this.OnDate_ReceivedChanging(value);
					this.SendPropertyChanging();
					this._Date_Received = value;
					this.SendPropertyChanged("Date_Received");
					this.OnDate_ReceivedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Enter Date]", Storage="_Enter_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Enter_Date
		{
			get
			{
				return this._Enter_Date;
			}
			set
			{
				if ((this._Enter_Date != value))
				{
					this.OnEnter_DateChanging(value);
					this.SendPropertyChanging();
					this._Enter_Date = value;
					this.SendPropertyChanged("Enter_Date");
					this.OnEnter_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Check Date]", Storage="_Check_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Check_Date
		{
			get
			{
				return this._Check_Date;
			}
			set
			{
				if ((this._Check_Date != value))
				{
					this.OnCheck_DateChanging(value);
					this.SendPropertyChanging();
					this._Check_Date = value;
					this.SendPropertyChanged("Check_Date");
					this.OnCheck_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Invoice to Received days]", Storage="_Invoice_to_Received_days", DbType="Float")]
		public System.Nullable<double> Invoice_to_Received_days
		{
			get
			{
				return this._Invoice_to_Received_days;
			}
			set
			{
				if ((this._Invoice_to_Received_days != value))
				{
					this.OnInvoice_to_Received_daysChanging(value);
					this.SendPropertyChanging();
					this._Invoice_to_Received_days = value;
					this.SendPropertyChanged("Invoice_to_Received_days");
					this.OnInvoice_to_Received_daysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Received to Check days]", Storage="_Received_to_Check_days", DbType="Float")]
		public System.Nullable<double> Received_to_Check_days
		{
			get
			{
				return this._Received_to_Check_days;
			}
			set
			{
				if ((this._Received_to_Check_days != value))
				{
					this.OnReceived_to_Check_daysChanging(value);
					this.SendPropertyChanging();
					this._Received_to_Check_days = value;
					this.SendPropertyChanged("Received_to_Check_days");
					this.OnReceived_to_Check_daysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Invoice to Check days]", Storage="_Invoice_to_Check_days", DbType="Float")]
		public System.Nullable<double> Invoice_to_Check_days
		{
			get
			{
				return this._Invoice_to_Check_days;
			}
			set
			{
				if ((this._Invoice_to_Check_days != value))
				{
					this.OnInvoice_to_Check_daysChanging(value);
					this.SendPropertyChanging();
					this._Invoice_to_Check_days = value;
					this.SendPropertyChanged("Invoice_to_Check_days");
					this.OnInvoice_to_Check_daysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Pmt Data]", Storage="_Pmt_Data", DbType="VarChar(10)")]
		public string Pmt_Data
		{
			get
			{
				return this._Pmt_Data;
			}
			set
			{
				if ((this._Pmt_Data != value))
				{
					this.OnPmt_DataChanging(value);
					this.SendPropertyChanging();
					this._Pmt_Data = value;
					this.SendPropertyChanged("Pmt_Data");
					this.OnPmt_DataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_check_no", DbType="VarChar(15)")]
		public string check_no
		{
			get
			{
				return this._check_no;
			}
			set
			{
				if ((this._check_no != value))
				{
					this.Oncheck_noChanging(value);
					this.SendPropertyChanging();
					this._check_no = value;
					this.SendPropertyChanged("check_no");
					this.Oncheck_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pmt_name", DbType="VarChar(30)")]
		public string pmt_name
		{
			get
			{
				return this._pmt_name;
			}
			set
			{
				if ((this._pmt_name != value))
				{
					this.Onpmt_nameChanging(value);
					this.SendPropertyChanging();
					this._pmt_name = value;
					this.SendPropertyChanged("pmt_name");
					this.Onpmt_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desc_30", DbType="VarChar(50)")]
		public string desc_30
		{
			get
			{
				return this._desc_30;
			}
			set
			{
				if ((this._desc_30 != value))
				{
					this.Ondesc_30Changing(value);
					this.SendPropertyChanging();
					this._desc_30 = value;
					this.SendPropertyChanged("desc_30");
					this.Ondesc_30Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="VarChar(50)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount", DbType="Float")]
		public System.Nullable<double> amount
		{
			get
			{
				return this._amount;
			}
			set
			{
				if ((this._amount != value))
				{
					this.OnamountChanging(value);
					this.SendPropertyChanging();
					this._amount = value;
					this.SendPropertyChanged("amount");
					this.OnamountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GL Acct]", Storage="_GL_Acct", DbType="VarChar(50)")]
		public string GL_Acct
		{
			get
			{
				return this._GL_Acct;
			}
			set
			{
				if ((this._GL_Acct != value))
				{
					this.OnGL_AcctChanging(value);
					this.SendPropertyChanging();
					this._GL_Acct = value;
					this.SendPropertyChanged("GL_Acct");
					this.OnGL_AcctChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GL Dept]", Storage="_GL_Dept", DbType="VarChar(50)")]
		public string GL_Dept
		{
			get
			{
				return this._GL_Dept;
			}
			set
			{
				if ((this._GL_Dept != value))
				{
					this.OnGL_DeptChanging(value);
					this.SendPropertyChanging();
					this._GL_Dept = value;
					this.SendPropertyChanged("GL_Dept");
					this.OnGL_DeptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Ledger/Batch]", Storage="_Ledger_Batch", DbType="VarChar(30)")]
		public string Ledger_Batch
		{
			get
			{
				return this._Ledger_Batch;
			}
			set
			{
				if ((this._Ledger_Batch != value))
				{
					this.OnLedger_BatchChanging(value);
					this.SendPropertyChanging();
					this._Ledger_Batch = value;
					this.SendPropertyChanged("Ledger_Batch");
					this.OnLedger_BatchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Requestor", DbType="VarChar(50)")]
		public string Requestor
		{
			get
			{
				return this._Requestor;
			}
			set
			{
				if ((this._Requestor != value))
				{
					this.OnRequestorChanging(value);
					this.SendPropertyChanging();
					this._Requestor = value;
					this.SendPropertyChanged("Requestor");
					this.OnRequestorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Last Access]", Storage="_Last_Access", DbType="VarChar(50)")]
		public string Last_Access
		{
			get
			{
				return this._Last_Access;
			}
			set
			{
				if ((this._Last_Access != value))
				{
					this.OnLast_AccessChanging(value);
					this.SendPropertyChanging();
					this._Last_Access = value;
					this.SendPropertyChanged("Last_Access");
					this.OnLast_AccessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Last Login]", Storage="_Last_Login", DbType="VarChar(50)")]
		public string Last_Login
		{
			get
			{
				return this._Last_Login;
			}
			set
			{
				if ((this._Last_Login != value))
				{
					this.OnLast_LoginChanging(value);
					this.SendPropertyChanging();
					this._Last_Login = value;
					this.SendPropertyChanged("Last_Login");
					this.OnLast_LoginChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="FMS.Contracts")]
	public partial class Contract
	{
		
		private int _Id;
		
		private System.Nullable<System.DateTime> _Doc_Date;
		
		private string _Clerk_Number;
		
		private string _Dept;
		
		private string _Sub_Doc;
		
		private string _Vendor;
		
		private string _Desc;
		
		private System.Nullable<System.DateTime> _Effective;
		
		private System.Nullable<System.DateTime> _Expires;
		
		private decimal _Expense;
		
		private decimal _Revenue;
		
		public Contract()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Doc Date]", Storage="_Doc_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Doc_Date
		{
			get
			{
				return this._Doc_Date;
			}
			set
			{
				if ((this._Doc_Date != value))
				{
					this._Doc_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Clerk Number]", Storage="_Clerk_Number", DbType="Char(20)")]
		public string Clerk_Number
		{
			get
			{
				return this._Clerk_Number;
			}
			set
			{
				if ((this._Clerk_Number != value))
				{
					this._Clerk_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dept", DbType="Char(50)")]
		public string Dept
		{
			get
			{
				return this._Dept;
			}
			set
			{
				if ((this._Dept != value))
				{
					this._Dept = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Sub-Doc]", Storage="_Sub_Doc", DbType="Char(50)")]
		public string Sub_Doc
		{
			get
			{
				return this._Sub_Doc;
			}
			set
			{
				if ((this._Sub_Doc != value))
				{
					this._Sub_Doc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vendor", DbType="Char(60)")]
		public string Vendor
		{
			get
			{
				return this._Vendor;
			}
			set
			{
				if ((this._Vendor != value))
				{
					this._Vendor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Desc]", Storage="_Desc", DbType="VarChar(8000)")]
		public string Desc
		{
			get
			{
				return this._Desc;
			}
			set
			{
				if ((this._Desc != value))
				{
					this._Desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Effective", DbType="Date")]
		public System.Nullable<System.DateTime> Effective
		{
			get
			{
				return this._Effective;
			}
			set
			{
				if ((this._Effective != value))
				{
					this._Effective = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expires", DbType="Date")]
		public System.Nullable<System.DateTime> Expires
		{
			get
			{
				return this._Expires;
			}
			set
			{
				if ((this._Expires != value))
				{
					this._Expires = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expense", DbType="Decimal(20,2) NOT NULL")]
		public decimal Expense
		{
			get
			{
				return this._Expense;
			}
			set
			{
				if ((this._Expense != value))
				{
					this._Expense = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Revenue", DbType="Decimal(20,2) NOT NULL")]
		public decimal Revenue
		{
			get
			{
				return this._Revenue;
			}
			set
			{
				if ((this._Revenue != value))
				{
					this._Revenue = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="FMS.depts_and_divisions")]
	public partial class depts_and_division
	{
		
		private string _dept_text;
		
		private System.Nullable<double> _dept_num;
		
		private string _division;
		
		private string _dept_name;
		
		public depts_and_division()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dept_text", DbType="NVarChar(255)")]
		public string dept_text
		{
			get
			{
				return this._dept_text;
			}
			set
			{
				if ((this._dept_text != value))
				{
					this._dept_text = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dept_num", DbType="Float")]
		public System.Nullable<double> dept_num
		{
			get
			{
				return this._dept_num;
			}
			set
			{
				if ((this._dept_num != value))
				{
					this._dept_num = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_division", DbType="NVarChar(255)")]
		public string division
		{
			get
			{
				return this._division;
			}
			set
			{
				if ((this._division != value))
				{
					this._division = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dept_name", DbType="NVarChar(255)")]
		public string dept_name
		{
			get
			{
				return this._dept_name;
			}
			set
			{
				if ((this._dept_name != value))
				{
					this._dept_name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="FMS.Expenditures")]
	public partial class Expenditure
	{
		
		private int _Id;
		
		private string _Department;
		
		private string _Service;
		
		private string _Fund_Group;
		
		private string _Category;
		
		private string _Description;
		
		private System.Nullable<int> _Year;
		
		private string _Vendor;
		
		private string _Check_ACH_Number;
		
		private System.Nullable<System.DateTime> _Check_Date;
		
		private System.Nullable<decimal> _Check_Amount;
		
		private string _Invoice_Number;
		
		private System.Nullable<System.DateTime> _Invoice_Date;
		
		private System.Nullable<decimal> _Invoice_Amount;
		
		private System.Nullable<decimal> _Check_Distribution;
		
		public Expenditure()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="VarChar(64)")]
		public string Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this._Department = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Service", DbType="VarChar(64)")]
		public string Service
		{
			get
			{
				return this._Service;
			}
			set
			{
				if ((this._Service != value))
				{
					this._Service = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fund_Group", DbType="VarChar(64)")]
		public string Fund_Group
		{
			get
			{
				return this._Fund_Group;
			}
			set
			{
				if ((this._Fund_Group != value))
				{
					this._Fund_Group = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="VarChar(64)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this._Category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(64)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="Int")]
		public System.Nullable<int> Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this._Year = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vendor", DbType="VarChar(64)")]
		public string Vendor
		{
			get
			{
				return this._Vendor;
			}
			set
			{
				if ((this._Vendor != value))
				{
					this._Vendor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Check_ACH_Number", DbType="VarChar(64)")]
		public string Check_ACH_Number
		{
			get
			{
				return this._Check_ACH_Number;
			}
			set
			{
				if ((this._Check_ACH_Number != value))
				{
					this._Check_ACH_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Check_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Check_Date
		{
			get
			{
				return this._Check_Date;
			}
			set
			{
				if ((this._Check_Date != value))
				{
					this._Check_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Check_Amount", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> Check_Amount
		{
			get
			{
				return this._Check_Amount;
			}
			set
			{
				if ((this._Check_Amount != value))
				{
					this._Check_Amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Invoice_Number", DbType="VarChar(64)")]
		public string Invoice_Number
		{
			get
			{
				return this._Invoice_Number;
			}
			set
			{
				if ((this._Invoice_Number != value))
				{
					this._Invoice_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Invoice_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Invoice_Date
		{
			get
			{
				return this._Invoice_Date;
			}
			set
			{
				if ((this._Invoice_Date != value))
				{
					this._Invoice_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Invoice_Amount", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> Invoice_Amount
		{
			get
			{
				return this._Invoice_Amount;
			}
			set
			{
				if ((this._Invoice_Amount != value))
				{
					this._Invoice_Amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Check_Distribution", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> Check_Distribution
		{
			get
			{
				return this._Check_Distribution;
			}
			set
			{
				if ((this._Check_Distribution != value))
				{
					this._Check_Distribution = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="FMS.AP_Measure_Final")]
	public partial class AP_Measure_Final
	{
		
		private System.Nullable<long> _RowId;
		
		private string _IndxCtrl;
		
		private string _AP_document;
		
		private string _vendor_number;
		
		private string _invoice_date;
		
		private string _received_date;
		
		private string _entered_date;
		
		private string _check_date;
		
		private System.Nullable<int> _check_month;
		
		private System.Nullable<int> _invoice_to_received;
		
		private System.Nullable<int> _received_to_check;
		
		private System.Nullable<int> _total_days;
		
		private string _payment_name;
		
		private System.Nullable<decimal> _total_amount;
		
		private string _GL_dept;
		
		private string _requestor;
		
		private string _last_access;
		
		private string _department;
		
		private string _division;
		
		private string _total_days_group;
		
		private string _exclude_filter;
		
		public AP_Measure_Final()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowId", DbType="BigInt")]
		public System.Nullable<long> RowId
		{
			get
			{
				return this._RowId;
			}
			set
			{
				if ((this._RowId != value))
				{
					this._RowId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IndxCtrl", DbType="VarChar(100)")]
		public string IndxCtrl
		{
			get
			{
				return this._IndxCtrl;
			}
			set
			{
				if ((this._IndxCtrl != value))
				{
					this._IndxCtrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AP_document", DbType="VarChar(50)")]
		public string AP_document
		{
			get
			{
				return this._AP_document;
			}
			set
			{
				if ((this._AP_document != value))
				{
					this._AP_document = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vendor_number", DbType="VarChar(10)")]
		public string vendor_number
		{
			get
			{
				return this._vendor_number;
			}
			set
			{
				if ((this._vendor_number != value))
				{
					this._vendor_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_invoice_date", DbType="VarChar(10)")]
		public string invoice_date
		{
			get
			{
				return this._invoice_date;
			}
			set
			{
				if ((this._invoice_date != value))
				{
					this._invoice_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_received_date", DbType="VarChar(10)")]
		public string received_date
		{
			get
			{
				return this._received_date;
			}
			set
			{
				if ((this._received_date != value))
				{
					this._received_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entered_date", DbType="VarChar(10)")]
		public string entered_date
		{
			get
			{
				return this._entered_date;
			}
			set
			{
				if ((this._entered_date != value))
				{
					this._entered_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_check_date", DbType="VarChar(10)")]
		public string check_date
		{
			get
			{
				return this._check_date;
			}
			set
			{
				if ((this._check_date != value))
				{
					this._check_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_check_month", DbType="Int")]
		public System.Nullable<int> check_month
		{
			get
			{
				return this._check_month;
			}
			set
			{
				if ((this._check_month != value))
				{
					this._check_month = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_invoice_to_received", DbType="Int")]
		public System.Nullable<int> invoice_to_received
		{
			get
			{
				return this._invoice_to_received;
			}
			set
			{
				if ((this._invoice_to_received != value))
				{
					this._invoice_to_received = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_received_to_check", DbType="Int")]
		public System.Nullable<int> received_to_check
		{
			get
			{
				return this._received_to_check;
			}
			set
			{
				if ((this._received_to_check != value))
				{
					this._received_to_check = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_days", DbType="Int")]
		public System.Nullable<int> total_days
		{
			get
			{
				return this._total_days;
			}
			set
			{
				if ((this._total_days != value))
				{
					this._total_days = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payment_name", DbType="VarChar(30)")]
		public string payment_name
		{
			get
			{
				return this._payment_name;
			}
			set
			{
				if ((this._payment_name != value))
				{
					this._payment_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_amount", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> total_amount
		{
			get
			{
				return this._total_amount;
			}
			set
			{
				if ((this._total_amount != value))
				{
					this._total_amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GL_dept", DbType="VarChar(4)")]
		public string GL_dept
		{
			get
			{
				return this._GL_dept;
			}
			set
			{
				if ((this._GL_dept != value))
				{
					this._GL_dept = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_requestor", DbType="VarChar(24)")]
		public string requestor
		{
			get
			{
				return this._requestor;
			}
			set
			{
				if ((this._requestor != value))
				{
					this._requestor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_access", DbType="VarChar(24)")]
		public string last_access
		{
			get
			{
				return this._last_access;
			}
			set
			{
				if ((this._last_access != value))
				{
					this._last_access = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_department", DbType="NVarChar(255)")]
		public string department
		{
			get
			{
				return this._department;
			}
			set
			{
				if ((this._department != value))
				{
					this._department = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_division", DbType="NVarChar(255)")]
		public string division
		{
			get
			{
				return this._division;
			}
			set
			{
				if ((this._division != value))
				{
					this._division = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_days_group", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string total_days_group
		{
			get
			{
				return this._total_days_group;
			}
			set
			{
				if ((this._total_days_group != value))
				{
					this._total_days_group = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exclude_filter", DbType="VarChar(11)")]
		public string exclude_filter
		{
			get
			{
				return this._exclude_filter;
			}
			set
			{
				if ((this._exclude_filter != value))
				{
					this._exclude_filter = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Abandoned_Property_Combined_Source")]
	public partial class Abandoned_Property_Combined_Source
	{
		
		private string _Parcel;
		
		private string _delFrom;
		
		private string _delTo;
		
		private System.Nullable<decimal> _totalAmt;
		
		private System.Nullable<decimal> _COS_lienAmt;
		
		private System.Nullable<System.DateTime> _waterShutoffDate;
		
		private string _Class;
		
		private System.Nullable<int> _DaysREO;
		
		private System.Nullable<System.DateTime> _AvistaShutoff;
		
		private string _prop_type;
		
		private string _site_address;
		
		private string _owner_name;
		
		private string _prop_use_desc;
		
		public Abandoned_Property_Combined_Source()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parcel", DbType="NVarChar(15)")]
		public string Parcel
		{
			get
			{
				return this._Parcel;
			}
			set
			{
				if ((this._Parcel != value))
				{
					this._Parcel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delFrom", DbType="VarChar(4)")]
		public string delFrom
		{
			get
			{
				return this._delFrom;
			}
			set
			{
				if ((this._delFrom != value))
				{
					this._delFrom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delTo", DbType="VarChar(4)")]
		public string delTo
		{
			get
			{
				return this._delTo;
			}
			set
			{
				if ((this._delTo != value))
				{
					this._delTo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalAmt", DbType="Money")]
		public System.Nullable<decimal> totalAmt
		{
			get
			{
				return this._totalAmt;
			}
			set
			{
				if ((this._totalAmt != value))
				{
					this._totalAmt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COS_lienAmt", DbType="Money")]
		public System.Nullable<decimal> COS_lienAmt
		{
			get
			{
				return this._COS_lienAmt;
			}
			set
			{
				if ((this._COS_lienAmt != value))
				{
					this._COS_lienAmt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_waterShutoffDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> waterShutoffDate
		{
			get
			{
				return this._waterShutoffDate;
			}
			set
			{
				if ((this._waterShutoffDate != value))
				{
					this._waterShutoffDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Class", DbType="NVarChar(255)")]
		public string Class
		{
			get
			{
				return this._Class;
			}
			set
			{
				if ((this._Class != value))
				{
					this._Class = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaysREO", DbType="Int")]
		public System.Nullable<int> DaysREO
		{
			get
			{
				return this._DaysREO;
			}
			set
			{
				if ((this._DaysREO != value))
				{
					this._DaysREO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvistaShutoff", DbType="DateTime")]
		public System.Nullable<System.DateTime> AvistaShutoff
		{
			get
			{
				return this._AvistaShutoff;
			}
			set
			{
				if ((this._AvistaShutoff != value))
				{
					this._AvistaShutoff = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prop_type", DbType="VarChar(1)")]
		public string prop_type
		{
			get
			{
				return this._prop_type;
			}
			set
			{
				if ((this._prop_type != value))
				{
					this._prop_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_site_address", DbType="VarChar(50)")]
		public string site_address
		{
			get
			{
				return this._site_address;
			}
			set
			{
				if ((this._site_address != value))
				{
					this._site_address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_owner_name", DbType="VarChar(40)")]
		public string owner_name
		{
			get
			{
				return this._owner_name;
			}
			set
			{
				if ((this._owner_name != value))
				{
					this._owner_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prop_use_desc", DbType="VarChar(40)")]
		public string prop_use_desc
		{
			get
			{
				return this._prop_use_desc;
			}
			set
			{
				if ((this._prop_use_desc != value))
				{
					this._prop_use_desc = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
